#!/usr/bin/awk -f
#
# cap-map-followers: Apply a map of word classifications to an input file of specific words to be classified.
# Output as TSV/CSV which then will need to be applied to the main file of results.
#
# Usage: cap-get-followers KWIC.tsv | cap-map-followers MAPFILE "-" | cap-apply-followers "-" KWIC.tsv > RESULTS.tsv
#
# by Eric Nystrom, http://ericnystrom.org
#   started: May 08, 2019
#   version: 
#
#   license: MIT License

BEGIN {
    FS = "\t";
    OFS = "\t";
}

# Process mapfile -- this is FOR NOW $1 count (disregarded), $2 term, $3 meaning (heritage/process)
# FOR NOW no header in the mapfile
NR == FNR {
    map[$2]=$3
}

# Process the output of cap-get-followers
# Includes header: cap-id	opintype	opinnum	casematch	opinmatch	followers
NR != FNR {

    # Header first line
    if (FNR == 1) {
	print $0, "meaning"
	next
    }

    # map each line and print
    print $0, map[$6]
}

    

    
